[package]
name = "pc-e220-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
pixels = "0.13.0"
winit = { version = "0.28", features = ["wayland"] }
iz80 = { git = "https://github.com/ivanizag/iz80" }
